import { PrismaClient, ContentCategory, SkillLevel } from "@prisma/client";

const prisma = new PrismaClient();

const BASE_URL = "https://medium.com/@s.sarathvarma";

const learningPaths = [
  {
    slug: "data-modeling",
    title: "Data Modeling Fundamentals",
    description:
      "Master data modeling concepts from logical and physical design to NoSQL, normalization, and real-world case studies. Essential for any data engineering interview.",
    icon: "🗄️",
    category: ContentCategory.DATA_MODELING,
    level: SkillLevel.BEGINNER,
    order: 1,
    modules: [
      {
        slug: "logical-data-modeling",
        title: "Logical Data Modeling",
        description: "Understand how to structure data for accuracy and integrity using ERDs, relationships, and business rules.",
        mediumUrl: `${BASE_URL}/logical-data-modeling-structuring-for-accuracy-and-integrity-788373974723`,
        readTimeMinutes: 12,
        order: 1,
      },
      {
        slug: "physical-data-modeling",
        title: "Physical Data Modeling",
        description: "Turn logical designs into implementation-ready schemas with indexes, partitions, and storage considerations.",
        mediumUrl: `${BASE_URL}/physical-data-modeling-implementation-ready-designs-d3795c0b32ed`,
        readTimeMinutes: 10,
        order: 2,
      },
      {
        slug: "normalization-denormalization",
        title: "Normalization & Denormalization",
        description: "Learn 1NF through BCNF normalization and when to denormalize for performance in analytical workloads.",
        mediumUrl: `${BASE_URL}/normalization-and-denormalization-explained-c720f735da69`,
        readTimeMinutes: 12,
        order: 3,
      },
      {
        slug: "nosql-big-data-modeling",
        title: "NoSQL & Big Data Modeling",
        description: "Advanced data modeling patterns for NoSQL systems including document, wide-column, and graph databases.",
        mediumUrl: `${BASE_URL}/advanced-data-modeling-for-nosql-and-big-data-96aceea4acf0`,
        readTimeMinutes: 14,
        order: 4,
      },
      {
        slug: "common-data-modeling-pitfalls",
        title: "Common Data Modeling Pitfalls",
        description: "Identify and avoid the most frequent mistakes in data modeling that tank production systems.",
        mediumUrl: `${BASE_URL}/common-pitfalls-in-data-modeling-and-how-to-avoid-them-5160a9bb382d`,
        readTimeMinutes: 10,
        order: 5,
      },
      {
        slug: "data-warehousing-modeling",
        title: "Data Warehousing & Analytics Modeling",
        description: "Star schemas, snowflake schemas, and dimensional modeling techniques for analytical systems.",
        mediumUrl: `${BASE_URL}/data-modeling-for-data-warehousing-and-analytics-74d67fb68bfa`,
        readTimeMinutes: 12,
        order: 6,
      },
      {
        slug: "data-modeling-case-studies",
        title: "Real-World Case Studies",
        description: "Apply data modeling concepts to real-world scenarios like e-commerce, social media, and financial systems.",
        mediumUrl: `${BASE_URL}/data-modeling-in-action-real-world-case-studies-dae1638fba22`,
        readTimeMinutes: 15,
        order: 7,
      },
    ],
  },
  {
    slug: "change-data-capture",
    title: "Change Data Capture (CDC)",
    description:
      "From the basics of CDC to building production log-based pipelines with Kafka and loading changes into data warehouses. One of the most tested topics in senior DE interviews.",
    icon: "🔄",
    category: ContentCategory.CDC,
    level: SkillLevel.INTERMEDIATE,
    order: 2,
    modules: [
      {
        slug: "cdc-comprehensive-guide",
        title: "Mastering CDC: A Comprehensive Guide",
        description: "An overview of Change Data Capture — what it is, why it matters, and how it fits into modern data architectures.",
        mediumUrl: `${BASE_URL}/mastering-change-data-capture-cdc-a-comprehensive-guide-c70d847bf4aa`,
        readTimeMinutes: 15,
        order: 1,
      },
      {
        slug: "cdc-environment-setup",
        title: "Setting Up Your CDC Environment",
        description: "Step-by-step setup of PostgreSQL, Debezium, and Docker for a local CDC development environment.",
        mediumUrl: `${BASE_URL}/setting-up-your-environment-for-cdc-385e1bc78f58`,
        readTimeMinutes: 12,
        order: 2,
      },
      {
        slug: "introduction-to-cdc",
        title: "Introduction to Change Data Capture",
        description: "Core CDC concepts: triggers, timestamps, log-based capture, and how each method compares for real workloads.",
        mediumUrl: `${BASE_URL}/introduction-to-change-data-capture-cdc-b7f762d5a135`,
        readTimeMinutes: 10,
        order: 3,
      },
      {
        slug: "log-based-cdc",
        title: "Getting Started with Log-Based CDC",
        description: "Deep dive into database transaction logs (WAL, binlog) and how Debezium reads them to capture changes.",
        mediumUrl: `${BASE_URL}/getting-started-with-log-based-cdc-55fbb48cba7e`,
        readTimeMinutes: 14,
        order: 4,
      },
      {
        slug: "building-log-reader",
        title: "Building a Basic Log Reader",
        description: "Hands-on: build a Python-based log reader that parses PostgreSQL WAL events into structured change records.",
        mediumUrl: `${BASE_URL}/building-a-basic-log-reader-60ad2a521780`,
        readTimeMinutes: 12,
        order: 5,
      },
      {
        slug: "kafka-for-cdc-scalability",
        title: "Introducing Kafka for Scalability",
        description: "Add Apache Kafka as the message bus between your CDC source and downstream consumers for durability and scale.",
        mediumUrl: `${BASE_URL}/introducing-kafka-for-scalability-ab349b2a4603`,
        readTimeMinutes: 13,
        order: 6,
      },
      {
        slug: "loading-changes-to-warehouse",
        title: "Loading Changes into a Data Warehouse",
        description: "Strategies for applying INSERT, UPDATE, DELETE events from CDC into BigQuery, Snowflake, or Redshift.",
        mediumUrl: `${BASE_URL}/loading-changes-into-a-data-warehouse-ac3f3fbb7106`,
        readTimeMinutes: 12,
        order: 7,
      },
      {
        slug: "schema-evolution-cdc",
        title: "Handling Schema Evolution",
        description: "Handle schema changes in upstream databases without breaking your CDC pipeline using Schema Registry and Avro.",
        mediumUrl: `${BASE_URL}/handling-schema-evolution-and-complex-scenarios-6b499c6013e8`,
        readTimeMinutes: 12,
        order: 8,
      },
      {
        slug: "monitoring-cdc-pipelines",
        title: "Monitoring & Optimizing CDC Pipelines",
        description: "Add observability — lag metrics, error tracking, dead-letter queues, and performance tuning for CDC at scale.",
        mediumUrl: `${BASE_URL}/monitoring-and-optimizing-cdc-pipelines-bb02297fef6a`,
        readTimeMinutes: 11,
        order: 9,
      },
      {
        slug: "advanced-cdc-use-cases",
        title: "Advanced CDC Use Cases & Extensions",
        description: "CDC for event sourcing, microservices sync, audit trails, and real-time ML feature pipelines.",
        mediumUrl: `${BASE_URL}/advanced-cdc-use-cases-and-extensions-50454aa7c45d`,
        readTimeMinutes: 14,
        order: 10,
      },
    ],
  },
  {
    slug: "gcp-data-engineering",
    title: "GCP Data Engineering Essentials",
    description:
      "Master Google Cloud Platform's core data services — BigQuery, Cloud Storage, Dataflow, and Cloud Composer — through hands-on tutorials and a capstone project.",
    icon: "☁️",
    category: ContentCategory.GCP,
    level: SkillLevel.BEGINNER,
    order: 3,
    modules: [
      {
        slug: "gcp-essentials-overview",
        title: "Master GCP Data Engineering Essentials",
        description: "Overview of GCP's data engineering ecosystem and how the services connect to form complete pipelines.",
        mediumUrl: `${BASE_URL}/master-gcp-data-engineering-essentials-e58e4b2d61ce`,
        readTimeMinutes: 10,
        order: 1,
      },
      {
        slug: "gcp-environment-setup",
        title: "Setting Up Your GCP Environment",
        description: "Create your GCP project, configure IAM, install the gcloud CLI, and set up billing alerts.",
        mediumUrl: `${BASE_URL}/setting-up-your-gcp-environment-b4640543136e`,
        readTimeMinutes: 10,
        order: 2,
      },
      {
        slug: "google-cloud-storage",
        title: "Google Cloud Storage",
        description: "Build scalable, secure data lakes on GCS — bucket configuration, lifecycle policies, and access control.",
        mediumUrl: `${BASE_URL}/google-cloud-storage-build-scalable-secure-data-lakes-1f3def050504`,
        readTimeMinutes: 12,
        order: 3,
      },
      {
        slug: "bigquery-fundamentals",
        title: "Google BigQuery: Scalable Data Analytics",
        description: "Get started with BigQuery — datasets, tables, partitioning, clustering, and writing your first analytical queries.",
        mediumUrl: `${BASE_URL}/google-bigquery-scalable-data-analytics-05781ca7689e`,
        readTimeMinutes: 14,
        order: 4,
      },
      {
        slug: "bigquery-advanced-queries",
        title: "Writing Advanced Queries in BigQuery",
        description: "Window functions, nested arrays, UNNEST, WITH clauses, and query optimization patterns for BigQuery.",
        mediumUrl: `${BASE_URL}/writing-advanced-queries-in-bigquery-2d883fbadff9`,
        readTimeMinutes: 15,
        order: 5,
      },
      {
        slug: "cloud-dataflow",
        title: "Cloud Dataflow: Unified Batch & Streaming",
        description: "Build Apache Beam pipelines on Cloud Dataflow for both batch ETL and real-time streaming workloads.",
        mediumUrl: `${BASE_URL}/cloud-dataflow-unified-batch-and-streaming-pipelines-4c001858c5b6`,
        readTimeMinutes: 13,
        order: 6,
      },
      {
        slug: "cloud-composer",
        title: "Cloud Composer: Workflow Orchestration",
        description: "Orchestrate complex multi-step data pipelines with Cloud Composer (managed Apache Airflow) on GCP.",
        mediumUrl: `${BASE_URL}/cloud-composer-workflow-orchestration-f4f7c3a7bf7f`,
        readTimeMinutes: 12,
        order: 7,
      },
      {
        slug: "gcp-capstone-project",
        title: "Capstone: End-to-End GCP Data Pipeline",
        description: "Build a complete data pipeline from GCS → Dataflow → BigQuery → Looker Studio using everything you've learned.",
        mediumUrl: `${BASE_URL}/capstone-project-build-an-end-to-end-data-pipeline-using-gcp-6f87c49985ff`,
        readTimeMinutes: 20,
        order: 8,
      },
    ],
  },
  {
    slug: "slowly-changing-dimensions",
    title: "Slowly Changing Dimensions (SCD)",
    description:
      "Master all SCD types — from Type 1 overwrites to Type 6 hybrid approaches — with practical SQL implementations for real data warehouse scenarios.",
    icon: "📅",
    category: ContentCategory.DATA_MODELING,
    level: SkillLevel.INTERMEDIATE,
    order: 4,
    modules: [
      {
        slug: "scd-overview",
        title: "Master Slowly Changing Dimensions",
        description: "Overview of why SCDs matter in data warehousing and how they preserve historical accuracy of dimension data.",
        mediumUrl: `${BASE_URL}/master-slowly-changing-dimensions-scd-in-data-warehousing-6ff2864894b6`,
        readTimeMinutes: 10,
        order: 1,
      },
      {
        slug: "scd-introduction",
        title: "Introduction to SCDs",
        description: "Deep dive into SCD concepts — surrogate keys, effective dates, current flags, and tracking history correctly.",
        mediumUrl: `${BASE_URL}/introduction-to-slowly-changing-dimensions-scd-fb1ecd9f7004`,
        readTimeMinutes: 10,
        order: 2,
      },
      {
        slug: "scd-types",
        title: "Exploring SCD Types",
        description: "Compare Type 0 through Type 6 with real examples showing when to use each type in production warehouses.",
        mediumUrl: `${BASE_URL}/exploring-different-types-of-slowly-changing-dimensions-scd-fa235573ddcc`,
        readTimeMinutes: 12,
        order: 3,
      },
      {
        slug: "scd-implementation",
        title: "Implementing SCDs in a Data Warehouse",
        description: "Hands-on SQL implementation of SCD Type 1, 2, and 3 using dbt and BigQuery/Snowflake.",
        mediumUrl: `${BASE_URL}/implementing-scd-in-a-data-warehouse-b7322e18dcf4`,
        readTimeMinutes: 15,
        order: 4,
      },
    ],
  },
  {
    slug: "gcp-advanced-services",
    title: "GCP Advanced Data Services",
    description:
      "Go beyond the basics with Pub/Sub for streaming, Dataproc for Spark workloads, Cloud SQL, Data Fusion, and IAM for enterprise-grade security.",
    icon: "⚡",
    category: ContentCategory.GCP,
    level: SkillLevel.INTERMEDIATE,
    order: 5,
    modules: [
      {
        slug: "gcp-advanced-overview",
        title: "Master GCP Advanced Data Engineering",
        description: "Overview of GCP's advanced data services and how they complement the core stack for complex pipelines.",
        mediumUrl: `${BASE_URL}/master-gcp-data-engineering-advanced-c7dff63394eb`,
        readTimeMinutes: 10,
        order: 1,
      },
      {
        slug: "cloud-pubsub",
        title: "Cloud Pub/Sub: Messaging & Real-Time Streaming",
        description: "Build event-driven architectures with Pub/Sub — topics, subscriptions, push vs pull, and ordering guarantees.",
        mediumUrl: `${BASE_URL}/google-cloud-pub-sub-messaging-real-time-streaming-ba29574498ef`,
        readTimeMinutes: 12,
        order: 2,
      },
      {
        slug: "google-dataproc",
        title: "Google Dataproc: Managed Hadoop & Spark",
        description: "Run Spark and Hadoop jobs on managed Dataproc clusters — autoscaling, job optimization, and cost control.",
        mediumUrl: `${BASE_URL}/google-dataproc-managed-hadoop-spark-33fb9fe821bc`,
        readTimeMinutes: 12,
        order: 3,
      },
      {
        slug: "cloud-sql",
        title: "Google Cloud SQL",
        description: "Scalable, secure transactional databases on Cloud — MySQL and PostgreSQL with HA, failover, and replication.",
        mediumUrl: `${BASE_URL}/google-cloud-sql-scalable-secure-transactional-databases-on-cloud-fec4563931cf`,
        readTimeMinutes: 11,
        order: 4,
      },
      {
        slug: "cloud-data-fusion",
        title: "Cloud Data Fusion: ETL/ELT Integration",
        description: "Build code-free and code-first ETL/ELT pipelines with Cloud Data Fusion's visual pipeline designer.",
        mediumUrl: `${BASE_URL}/cloud-data-fusion-etl-elt-integration-e42af663a7d0`,
        readTimeMinutes: 12,
        order: 5,
      },
      {
        slug: "gcp-iam",
        title: "IAM: Identity & Access Management",
        description: "Secure your GCP data infrastructure with IAM roles, service accounts, VPC controls, and least-privilege patterns.",
        mediumUrl: `${BASE_URL}/iam-identity-and-access-management-34e9c3619c18`,
        readTimeMinutes: 11,
        order: 6,
      },
    ],
  },
  {
    slug: "snowflake-performance",
    title: "Snowflake Query Performance",
    description:
      "Master Snowflake's performance optimization techniques — from table scan reduction and join optimization to caching strategies that cut costs and query times.",
    icon: "❄️",
    category: ContentCategory.SNOWFLAKE,
    level: SkillLevel.INTERMEDIATE,
    order: 6,
    modules: [
      {
        slug: "snowflake-performance-overview",
        title: "Ultimate Guide to Snowflake Query Performance",
        description: "Overview of Snowflake's query execution model and the optimization levers available to data engineers.",
        mediumUrl: `${BASE_URL}/ultimate-guide-to-snowflake-query-performance-best-practices-optimization-techniques-c51c1a380b67`,
        readTimeMinutes: 12,
        order: 1,
      },
      {
        slug: "snowflake-best-practices",
        title: "Snowflake Query Performance: Best Practices",
        description: "Foundational best practices for writing cost-effective, fast queries in Snowflake at scale.",
        mediumUrl: `${BASE_URL}/snowflake-query-performance-optimization-best-practices-for-faster-cost-effective-queries-4b92c8eb789b`,
        readTimeMinutes: 12,
        order: 2,
      },
      {
        slug: "snowflake-table-scan",
        title: "Snowflake Table Scan Optimization",
        description: "Reduce data read through micro-partition pruning, clustering keys, and column selection strategies.",
        mediumUrl: `${BASE_URL}/snowflake-table-scan-optimization-reduce-data-read-and-boost-query-speed-8aa7efb03596`,
        readTimeMinutes: 12,
        order: 3,
      },
      {
        slug: "snowflake-join-optimization",
        title: "Snowflake Join Optimization",
        description: "Optimize multi-table joins using broadcast joins, join order, and understanding Snowflake's query planner.",
        mediumUrl: `${BASE_URL}/snowflake-join-optimization-improve-query-performance-and-reduce-compute-costs-24900016da46`,
        readTimeMinutes: 12,
        order: 4,
      },
      {
        slug: "snowflake-sorting-aggregation",
        title: "Sorting & Aggregation Optimization",
        description: "Speed up GROUP BY, ORDER BY, and window functions using materialized views and result caching.",
        mediumUrl: `${BASE_URL}/snowflake-sorting-aggregation-optimization-speed-up-queries-and-reduce-costs-994e58f47fec`,
        readTimeMinutes: 11,
        order: 5,
      },
      {
        slug: "snowflake-caching",
        title: "Maximizing Snowflake Caching Efficiency",
        description: "Leverage result cache, local disk cache, and remote storage cache for faster queries and lower credits.",
        mediumUrl: `${BASE_URL}/maximizing-snowflake-caching-efficiency-faster-queries-lower-costs-e7dcf94ea4a7`,
        readTimeMinutes: 11,
        order: 6,
      },
    ],
  },
  {
    slug: "cicd-data-engineering",
    title: "CI/CD for Data Engineering",
    description:
      "Build production-grade CI/CD pipelines for data teams using GitHub Actions — from automating dbt tests to deploying Airflow DAGs safely.",
    icon: "🚀",
    category: ContentCategory.CI_CD,
    level: SkillLevel.INTERMEDIATE,
    order: 7,
    modules: [
      {
        slug: "cicd-overview",
        title: "Master CI/CD with GitHub Actions",
        description: "Why data engineering teams need CI/CD and how GitHub Actions changes how you ship data pipelines.",
        mediumUrl: `${BASE_URL}/master-ci-cd-with-github-actions-for-data-engineering-teams-803721522b72`,
        readTimeMinutes: 10,
        order: 1,
      },
      {
        slug: "github-actions-basics",
        title: "GitHub Actions Basics & Setup",
        description: "Write your first workflow — triggers, jobs, steps, secrets management, and matrix builds for data pipelines.",
        mediumUrl: `${BASE_URL}/github-actions-basics-and-setting-up-for-data-engineering-4e267f0a0a20`,
        readTimeMinutes: 12,
        order: 2,
      },
      {
        slug: "cicd-for-dbt",
        title: "Building a CI/CD Pipeline for dbt Projects",
        description: "Automate dbt test runs on PRs, deploy to production on merge, and manage environment promotion safely.",
        mediumUrl: `${BASE_URL}/building-a-ci-cd-pipeline-for-dbt-projects-6b09b2f3f027`,
        readTimeMinutes: 15,
        order: 3,
      },
    ],
  },
  {
    slug: "modern-data-architecture",
    title: "Modern Data Architecture",
    description:
      "Understand how leading companies architect their data platforms — Medallion architecture, the lakehouse paradigm, data observability, and data contracts.",
    icon: "🏗️",
    category: ContentCategory.DATA_ARCHITECTURE,
    level: SkillLevel.INTERMEDIATE,
    order: 8,
    modules: [
      {
        slug: "medallion-architecture",
        title: "Medallion Architecture: Layers of a Lakehouse",
        description: "Design Bronze → Silver → Gold data layers for reliable, testable, and incrementally refining data pipelines.",
        mediumUrl: `${BASE_URL}/understanding-medallion-architecture-layers-of-a-lakehouse-804ad60a55fc`,
        readTimeMinutes: 12,
        order: 1,
      },
      {
        slug: "dw-vs-lake-vs-lakehouse",
        title: "Data Warehouse vs Data Lake vs Lakehouse",
        description: "Compare architectures across cost, latency, governance, and flexibility to choose the right pattern for your use case.",
        mediumUrl: `${BASE_URL}/data-warehouse-vs-data-lake-vs-data-lakehouse-guide-to-modern-data-architectures-b5fb96e3cb4c`,
        readTimeMinutes: 13,
        order: 2,
      },
      {
        slug: "data-observability",
        title: "Data Observability: Why It's Essential",
        description: "Build data quality monitoring — freshness, volume, schema drift, and lineage — to catch problems before users do.",
        mediumUrl: `${BASE_URL}/data-observability-why-its-essential-for-reliable-data-b43793d1c048`,
        readTimeMinutes: 12,
        order: 3,
      },
      {
        slug: "data-contracts",
        title: "Data Contracts: The Fix Your Platform Needs",
        description: "Define schema contracts between producers and consumers to prevent breaking changes from cascading downstream.",
        mediumUrl: `${BASE_URL}/data-contracts-the-fix-your-data-platform-needs-6cc7afa097d2`,
        readTimeMinutes: 12,
        order: 4,
      },
    ],
  },
  {
    slug: "databricks",
    title: "Databricks Data Engineering",
    description:
      "Get hands-on with Databricks — from setting up your environment to building production pipelines on the Lakehouse platform with Delta Lake and Unity Catalog.",
    icon: "🔥",
    category: ContentCategory.DATABRICKS,
    level: SkillLevel.INTERMEDIATE,
    order: 9,
    modules: [
      {
        slug: "databricks-essentials",
        title: "Mastering Databricks Data Engineering Essentials",
        description: "Overview of Databricks' core components — clusters, notebooks, Delta Lake, and the Lakehouse architecture.",
        mediumUrl: `${BASE_URL}/mastering-databricks-data-engineering-essentials-a08ed3a4e44b`,
        readTimeMinutes: 12,
        order: 1,
      },
      {
        slug: "databricks-environment-setup",
        title: "Setting Up Your Databricks Environment",
        description: "Create workspace, configure clusters, set up Unity Catalog, and connect to cloud storage — step by step.",
        mediumUrl: `${BASE_URL}/setting-up-your-databricks-environment-42093c217ea1`,
        readTimeMinutes: 12,
        order: 2,
      },
      {
        slug: "databricks-lakehouse-platform",
        title: "Databricks Lakehouse Platform",
        description: "Unified data engineering with Delta Live Tables, Auto Loader, and Workflows for production-grade pipelines.",
        mediumUrl: `${BASE_URL}/databricks-lakehouse-platform-unified-data-engineering-3991bf0ced55`,
        readTimeMinutes: 14,
        order: 3,
      },
    ],
  },
  {
    slug: "system-design",
    title: "Data Engineering System Design",
    description:
      "Ace system design interviews with a structured framework and real-world case studies — clickstream pipelines, CDC architectures, API ingestion, and batch processing.",
    icon: "📐",
    category: ContentCategory.SYSTEM_DESIGN,
    level: SkillLevel.ADVANCED,
    order: 10,
    modules: [
      {
        slug: "system-design-framework",
        title: "Data Engineering System Design Framework",
        description: "A repeatable framework for answering data engineering system design questions in interviews with confidence.",
        mediumUrl: `${BASE_URL}/data-engineering-system-design-6764e0a72e3d`,
        readTimeMinutes: 15,
        order: 1,
      },
      {
        slug: "clickstream-pipeline-design",
        title: "Clickstream Pipeline Design",
        description: "Design a clickstream ingestion pipeline from web events → Kafka → lakehouse at 1M+ events/second.",
        mediumUrl: `${BASE_URL}/data-engineering-system-design-clickstream-data-into-a-modern-lakehouse-b977696030f7`,
        readTimeMinutes: 18,
        order: 2,
      },
      {
        slug: "cdc-pipeline-design",
        title: "CDC-Based Pipeline: OLTP to Lakehouse",
        description: "Design a CDC pipeline from a transactional database to a lakehouse with sub-second latency requirements.",
        mediumUrl: `${BASE_URL}/data-engineering-system-design-building-a-cdc-based-pipeline-from-oltp-to-a-lakehouse-e705c9be7ea6`,
        readTimeMinutes: 18,
        order: 3,
      },
      {
        slug: "api-ingestion-pipeline-design",
        title: "API Ingestion Pipeline Design",
        description: "Design a system to ingest external APIs reliably into a data warehouse with rate limiting, retries, and backfill.",
        mediumUrl: `${BASE_URL}/data-engineering-system-design-ingesting-external-apis-into-a-modern-data-warehouse-eecb715da1b2`,
        readTimeMinutes: 17,
        order: 4,
      },
      {
        slug: "batch-processing-design",
        title: "Daily Batch Processing Design",
        description: "Design a daily batch pipeline from cloud storage files to a warehouse with exactly-once semantics and SLA guarantees.",
        mediumUrl: `${BASE_URL}/data-engineering-system-design-daily-batch-processing-from-cloud-storage-into-a-modern-warehouse-e93a5dc0b091`,
        readTimeMinutes: 17,
        order: 5,
      },
    ],
  },
  {
    slug: "ai-engineering",
    title: "AI Engineering Fundamentals",
    description:
      "Understand how LLMs actually work — from tokenization and embeddings to RAG architectures and hallucination mitigation. Essential for data engineers moving into AI.",
    icon: "🤖",
    category: ContentCategory.AI_ENGINEERING,
    level: SkillLevel.INTERMEDIATE,
    order: 11,
    modules: [
      {
        slug: "llm-internals",
        title: "LLM Internals: From Prompt to Answer",
        description: "How large language models process your prompt — attention mechanisms, transformer layers, and inference explained simply.",
        mediumUrl: `${BASE_URL}/llm-internals-for-everyone-from-prompt-to-answer-9f2819c9b48d`,
        readTimeMinutes: 15,
        order: 1,
      },
      {
        slug: "tokenization",
        title: "Tokenization Explained",
        description: "How AI breaks language into tokens — BPE, vocabulary size, token limits, and why tokenization shapes model behavior.",
        mediumUrl: `${BASE_URL}/tokenization-explained-how-ai-breaks-language-into-tokens-38b2ce51a1d9`,
        readTimeMinutes: 12,
        order: 2,
      },
      {
        slug: "embeddings",
        title: "Embeddings Explained: How AI Understands Meaning",
        description: "What embeddings are, how they're generated, and how semantic similarity powers search, recommendations, and RAG.",
        mediumUrl: `${BASE_URL}/embeddings-explained-how-ai-understands-meaning-77c0c09cc072`,
        readTimeMinutes: 12,
        order: 3,
      },
      {
        slug: "vector-databases",
        title: "Vector Databases Explained",
        description: "How vector databases like Pinecone, Weaviate, and pgvector store and search embeddings for AI applications.",
        mediumUrl: `${BASE_URL}/vector-databases-explained-how-ai-searches-using-meaning-ee1301fa77c3`,
        readTimeMinutes: 13,
        order: 4,
      },
      {
        slug: "rag-explained",
        title: "RAG Explained: How AI Answers Using Your Data",
        description: "Build Retrieval-Augmented Generation systems that ground LLM responses in your own documents and databases.",
        mediumUrl: `${BASE_URL}/rag-explained-how-ai-answers-using-your-data-4c91d15f0fee`,
        readTimeMinutes: 14,
        order: 5,
      },
      {
        slug: "llm-hallucinations",
        title: "Why LLMs Hallucinate (And How to Reduce It)",
        description: "Understand why LLMs produce false information and the practical techniques to detect and mitigate hallucinations.",
        mediumUrl: `${BASE_URL}/why-llms-hallucinate-and-how-to-reduce-it-47ecba4bfdda`,
        readTimeMinutes: 12,
        order: 6,
      },
    ],
  },
  {
    slug: "open-table-formats",
    title: "Open Table Formats",
    description:
      "Master the open table format landscape — Apache Iceberg, Apache Hudi, and Delta Lake — and understand when to use each for your lakehouse architecture.",
    icon: "📦",
    category: ContentCategory.OPEN_TABLE_FORMATS,
    level: SkillLevel.ADVANCED,
    order: 12,
    modules: [
      {
        slug: "open-table-formats-overview",
        title: "Open Table Formats: Overview",
        description: "Why open table formats exist, what problems they solve, and how Iceberg, Hudi, and Delta Lake compare.",
        mediumUrl: `${BASE_URL}/open-table-formats-4c15625c7bdb`,
        readTimeMinutes: 12,
        order: 1,
      },
      {
        slug: "apache-iceberg",
        title: "Apache Iceberg",
        description: "Deep dive into Iceberg — hidden partitioning, time travel, schema evolution, and why Netflix, Apple, and AWS chose it.",
        mediumUrl: `${BASE_URL}/apache-iceberg-f307c57effc4`,
        readTimeMinutes: 14,
        order: 2,
      },
      {
        slug: "apache-hudi",
        title: "Apache Hudi",
        description: "How Uber's data lake format handles upserts and deletes with Copy-on-Write and Merge-on-Read table types.",
        mediumUrl: `${BASE_URL}/apache-hudi-8e56d5bc244e`,
        readTimeMinutes: 13,
        order: 3,
      },
      {
        slug: "delta-lake",
        title: "Delta Lake",
        description: "Databricks' open table format — ACID transactions, Z-ordering, Liquid Clustering, and the Delta Log explained.",
        mediumUrl: `${BASE_URL}/delta-lake-4990fd26e2f7`,
        readTimeMinutes: 13,
        order: 4,
      },
    ],
  },
  {
    slug: "essential-skills",
    title: "Essential Data Engineering Skills",
    description:
      "Core skills every data engineer needs — Python coding patterns for interviews, Git commands, partitioning strategies, and platform comparison knowledge.",
    icon: "🛠️",
    category: ContentCategory.ESSENTIAL_SKILLS,
    level: SkillLevel.BEGINNER,
    order: 13,
    modules: [
      {
        slug: "python-interview-patterns",
        title: "Python Coding Interview Patterns",
        description: "The most common Python patterns tested in data engineering interviews — generators, decorators, list comprehensions, and more.",
        mediumUrl: `${BASE_URL}/python-coding-interview-patterns-510c0446daf2`,
        readTimeMinutes: 15,
        order: 1,
      },
      {
        slug: "data-modeling-for-interviews",
        title: "Data Engineering Data Modeling for Interviews",
        description: "How to approach data modeling questions in interviews — what interviewers look for and how to structure your answer.",
        mediumUrl: `${BASE_URL}/data-engineering-data-modeling-ca922d70fbc3`,
        readTimeMinutes: 12,
        order: 2,
      },
      {
        slug: "partitioning-clustering-sharding",
        title: "Partitioning, Clustering & Sharding",
        description: "Understand how data distribution strategies — partitioning, clustering, and sharding — boost performance at scale.",
        mediumUrl: `${BASE_URL}/partitioning-clustering-sharding-boost-performance-78ad01f132f2`,
        readTimeMinutes: 13,
        order: 3,
      },
      {
        slug: "git-commands",
        title: "Master Git Commands: A Hands-On Tutorial",
        description: "The Git commands every data engineer needs — branching, rebasing, cherry-picking, and resolving merge conflicts.",
        mediumUrl: `${BASE_URL}/master-git-commands-a-hands-on-tutorial-bc33aca2c3a2`,
        readTimeMinutes: 12,
        order: 4,
      },
      {
        slug: "databricks-vs-snowflake",
        title: "Databricks vs Snowflake: Which Platform Fits?",
        description: "A practical comparison of Databricks and Snowflake across cost, performance, ecosystem, and use case fit.",
        mediumUrl: `${BASE_URL}/databricks-vs-snowflake-which-cloud-data-platform-fits-your-needs-403fc4b5d219`,
        readTimeMinutes: 12,
        order: 5,
      },
    ],
  },
];

async function main() {
  console.log("🌱 Seeding learning content...");

  for (const pathData of learningPaths) {
    const { modules, ...pathFields } = pathData;

    const path = await prisma.learningPath.upsert({
      where: { slug: pathFields.slug },
      update: {
        title: pathFields.title,
        description: pathFields.description,
        icon: pathFields.icon,
        category: pathFields.category,
        level: pathFields.level,
        order: pathFields.order,
      },
      create: pathFields,
    });

    for (const mod of modules) {
      await prisma.learningModule.upsert({
        where: { pathId_slug: { pathId: path.id, slug: mod.slug } },
        update: {
          title: mod.title,
          description: mod.description,
          mediumUrl: mod.mediumUrl,
          readTimeMinutes: mod.readTimeMinutes,
          order: mod.order,
        },
        create: {
          ...mod,
          pathId: path.id,
        },
      });
    }

    console.log(`  ✅ ${pathFields.title} (${modules.length} modules)`);
  }

  const totalModules = learningPaths.reduce((sum, p) => sum + p.modules.length, 0);
  console.log(`\n✨ Seeded ${learningPaths.length} learning paths with ${totalModules} total modules.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
